### ISSUE TITLE
NixOS Readme package didn't work

### ISSUE THREAD

**Issue by KenMacD** [oddlama/whisper-overlay#1]
I'm not sure if it's an overlay issue or what, but the instructions for NixOS where it says:

```nix
environment.systemPackages = [pkgs.whisper-overlay];
```

throws an error as it's unable to find the package. For testing it locally for now I'm just using:

```nix
environment.systemPackages = [
  inputs.whisper-overlay.packages.${system}.whisper-overlay
];
```

**Comment by oddlama** [comment]
The package only works that way if you add the NixOS module, which will then automatically add an overlay to your nixpkgs instanciation. But what you are doing right now is fine too.

**Comment by KenMacD** [comment]
Strange. I was using it as a module. In my `flake.nix` I had:

```nix
hostname = nixpkgs.lib.nixosSystem {
  inherit system;
  specialArgs = {inherit self system inputs;};
  modules = [
    ({...}: {
      imports = [
        inputs.whisper-overlay.nixosModules.default
      ];
      services.realtime-stt-server.enable = true;
      environment.systemPackages = [
        pkgs.whisper-overlay
      ];
    })
```

and it seemed like the overlay didn't apply. No biggie though.
